; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32@6.3.2
board = esp32dev
framework = espidf

board_build.partitions = partitions.csv
board_upload.flash_size = 4MB

build_unflags = -std=gnu++11 -std=gnu++14
build_flags = 
    -std=gnu++17
    -DCONFIG_ARDUINOJSON_ENABLE_STD_STRING=1
    -DCONFIG_LOG_COLORS_ENABLE=0
    -Os
    -ffunction-sections
    -fdata-sections

board_build.sdkconfig_options =
    CONFIG_FREERTOS_HZ=1000
    CONFIG_ESP_MAIN_TASK_STACK_SIZE=8192
    CONFIG_COMPILER_CXX_EXCEPTIONS=y
    CONFIG_COMPILER_CXX_EXCEPTIONS_EMG_POOL_SIZE=0
    CONFIG_MQTT_ENABLED=y
    CONFIG_ESPTOOLPY_FLASHSIZE_4MB=y
    CONFIG_PARTITION_TABLE_SINGLE_APP_LARGE=y
    CONFIG_COMPILER_OPTIMIZATION_SIZE=y
    CONFIG_NEWLIB_NANO_FORMAT=y

monitor_speed = 115200
extra_scripts = pre:script/env_loader.py

lib_deps =
    bblanchon/ArduinoJson@^7.0.0